console.log("Hey Abu Hurairah, I have started learning typescript");
var userName = "Asma Yameen";
console.log(userName);
var a = 5;
var b = 10;
var c = 12;
var d = 14;
var e = 16;
var f = 18;
var g = 20;
var h = 22;
var i = 24;
var j = 26;
var Sum = a + b + c + d + e + f + g + h + i + j;
console.log(Sum);
var difference = g - c;
console.log(difference);
var product = a * b * c * d * e * f * g * h * i * j;
console.log(product);
var division = g / a;